import { useState, useEffect } from "react";
import api from "@/lib/api";
import LimitBanner from "@/components/LimitBanner";

interface Flashcard {
  front: string;
  back: string;
}

type CardStatus = "unseen" | "known" | "unknown";

export default function Flashcards() {
  const [text,        setText]        = useState("");
  const [count,       setCount]       = useState(10);
  const [cards,       setCards]       = useState<Flashcard[]>([]);
  const [statuses,    setStatuses]    = useState<CardStatus[]>([]);
  const [loading,     setLoading]     = useState(false);
  const [limitReached,setLimitReached]= useState(false);
  const [error,       setError]       = useState("");
  const [current,     setCurrent]     = useState(0);
  const [flipped,     setFlipped]     = useState(false);

  // Auto-load cards generated by an AI action session
  useEffect(() => {
    const stored = sessionStorage.getItem("ai_generated_flashcards");
    if (stored) {
      try {
        const fc: Flashcard[] = JSON.parse(stored);
        if (Array.isArray(fc) && fc.length > 0) {
          setCards(fc);
          setStatuses(new Array(fc.length).fill("unseen"));
          setCurrent(0);
          setFlipped(false);
        }
      } catch { /* ignore malformed data */ }
      sessionStorage.removeItem("ai_generated_flashcards");
    }
  }, []);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (text.trim().length < 10) { setError("Please enter at least 10 characters."); return; }
    setError(""); setLimitReached(false); setCards([]); setCurrent(0); setFlipped(false);
    setLoading(true);
    try {
      const { data } = await api.post("/study-tools/flashcards", { text, count });
      const fc: Flashcard[] = data.data.flashcards;
      setCards(fc);
      setStatuses(new Array(fc.length).fill("unseen"));
    } catch (err: any) {
      if (err?.response?.data?.limitReached) setLimitReached(true);
      else setError(err?.response?.data?.message || "Failed to generate flashcards.");
    } finally {
      setLoading(false);
    }
  };

  const next = () => {
    if (current < cards.length - 1) { setCurrent(p => p + 1); setFlipped(false); }
  };
  const prev = () => {
    if (current > 0) { setCurrent(p => p - 1); setFlipped(false); }
  };

  const markCard = (status: "known" | "unknown") => {
    setStatuses(prev => {
      const next = [...prev];
      next[current] = status;
      return next;
    });
    if (current < cards.length - 1) {
      setTimeout(() => { setCurrent(p => p + 1); setFlipped(false); }, 300);
    }
  };

  const restart = () => {
    setCurrent(0);
    setFlipped(false);
    setStatuses(new Array(cards.length).fill("unseen"));
  };

  const known   = statuses.filter(s => s === "known").length;
  const unknown = statuses.filter(s => s === "unknown").length;
  const isEnd   = current === cards.length - 1 && statuses[current] !== "unseen";

  /* ── Input view ─────────────────────────────────────────────────────── */
  if (cards.length === 0) {
    return (
      <div className="max-w-3xl space-y-8">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight">Flashcards</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Paste your study material and generate interactive flashcards.
          </p>
        </div>

        {limitReached && <LimitBanner feature="flashcards" />}

        <div className="bg-card border border-border rounded-2xl p-6 space-y-5">
          <form onSubmit={handleGenerate} className="space-y-5">
            {/* Textarea */}
            <div>
              <label className="flex items-center justify-between text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
                <span>Study Material</span>
                <span className="font-normal normal-case text-muted-foreground/60">{text.length} / 5000</span>
              </label>
              <textarea
                data-testid="input-text"
                value={text}
                onChange={e => setText(e.target.value.slice(0, 5000))}
                rows={8}
                placeholder="Paste your notes, textbook passages, or any content you want to memorise…"
                className="w-full px-4 py-3 rounded-xl border border-input bg-background text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-all resize-none"
              />
            </div>

            {/* Count slider */}
            <div>
              <label className="flex items-center justify-between text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">
                <span>Number of cards</span>
                <span className="font-bold text-foreground text-sm">{count}</span>
              </label>
              <div className="flex items-center gap-3">
                <span className="text-xs text-muted-foreground w-4">5</span>
                <input
                  data-testid="select-count"
                  type="range"
                  min={5}
                  max={20}
                  step={1}
                  value={count}
                  onChange={e => setCount(Number(e.target.value))}
                  className="flex-1 h-1.5 rounded-full accent-primary bg-muted cursor-pointer"
                />
                <span className="text-xs text-muted-foreground w-5">20</span>
              </div>
              <div className="flex justify-between mt-2">
                {[5, 10, 15, 20].map(n => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => setCount(n)}
                    className={`text-[10px] font-semibold px-2 py-0.5 rounded border transition-all ${
                      count === n
                        ? "bg-primary text-white border-primary"
                        : "border-border text-muted-foreground hover:text-foreground"
                    }`}
                  >{n}</button>
                ))}
              </div>
            </div>

            {error && (
              <p className="text-sm text-destructive flex items-center gap-1.5">
                <i className="fa-solid fa-circle-exclamation" />{error}
              </p>
            )}

            <button
              data-testid="btn-generate"
              type="submit"
              disabled={loading || text.trim().length < 10}
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl text-sm font-semibold text-white bg-primary hover:bg-primary/90 transition-all disabled:opacity-50"
            >
              {loading ? (
                <><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Generating cards…</>
              ) : (
                <><i className="fa-solid fa-layer-group" />Generate {count} Flashcards</>
              )}
            </button>
          </form>
        </div>

        {/* Skeleton loading preview */}
        {loading && (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {Array.from({ length: count > 6 ? 6 : count }).map((_, i) => (
              <div key={i} className="h-28 bg-card border border-border rounded-2xl animate-pulse" />
            ))}
          </div>
        )}
      </div>
    );
  }

  /* ── Study view ─────────────────────────────────────────────────────── */
  return (
    <div className="max-w-3xl space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight">Flashcards</h1>
          <p className="text-muted-foreground text-xs mt-0.5">
            {known} known · {unknown} to review · {cards.length - known - unknown} unseen
          </p>
        </div>
        <button
          data-testid="btn-new-cards"
          onClick={() => setCards([])}
          className="flex items-center gap-2 px-4 py-2 rounded-xl border border-border text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-all"
        >
          <i className="fa-solid fa-plus" />
          New set
        </button>
      </div>

      {/* Progress bar */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>Card {current + 1} of {cards.length}</span>
          <span>{Math.round(((known + unknown) / cards.length) * 100)}% reviewed</span>
        </div>
        <div className="h-1.5 rounded-full bg-muted overflow-hidden flex">
          <div className="bg-emerald-400 transition-all duration-300" style={{ width: `${(known / cards.length) * 100}%` }} />
          <div className="bg-red-400 transition-all duration-300" style={{ width: `${(unknown / cards.length) * 100}%` }} />
        </div>
      </div>

      {/* Flip card */}
      <div className="w-full [perspective:1200px] cursor-pointer select-none" onClick={() => setFlipped(f => !f)}>
        <div
          className={`relative w-full h-56 transition-transform duration-500 [transform-style:preserve-3d] ${
            flipped ? "[transform:rotateY(180deg)]" : ""
          }`}
        >
          {/* Front */}
          <div className="absolute inset-0 bg-card border-2 border-border rounded-2xl flex flex-col items-center justify-center p-8 [backface-visibility:hidden] shadow-sm">
            <span className="text-[10px] font-bold text-primary uppercase tracking-widest mb-4">Question</span>
            <p className="text-foreground font-semibold text-center text-base leading-relaxed">
              {cards[current]?.front}
            </p>
            <span className="absolute bottom-4 text-xs text-muted-foreground/60 flex items-center gap-1.5">
              <i className="fa-solid fa-hand-pointer text-[10px]" />
              Click to reveal answer
            </span>
          </div>
          {/* Back */}
          <div className="absolute inset-0 bg-primary/5 border-2 border-primary/30 rounded-2xl flex flex-col items-center justify-center p-8 [backface-visibility:hidden] [transform:rotateY(180deg)] shadow-sm">
            <span className="text-[10px] font-bold text-primary uppercase tracking-widest mb-4">Answer</span>
            <p className="text-foreground font-medium text-center text-base leading-relaxed">
              {cards[current]?.back}
            </p>
          </div>
        </div>
      </div>

      {/* Known / Unknown buttons */}
      {flipped && !isEnd && (
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={() => markCard("unknown")}
            className="flex items-center justify-center gap-2 py-3 rounded-xl border border-red-400/30 bg-red-400/5 text-red-400 text-sm font-semibold hover:bg-red-400/10 transition-all"
          >
            <i className="fa-solid fa-xmark" />
            Still Learning
          </button>
          <button
            onClick={() => markCard("known")}
            className="flex items-center justify-center gap-2 py-3 rounded-xl border border-emerald-400/30 bg-emerald-400/5 text-emerald-400 text-sm font-semibold hover:bg-emerald-400/10 transition-all"
          >
            <i className="fa-solid fa-check" />
            Got It
          </button>
        </div>
      )}

      {/* Navigation controls */}
      <div className="flex items-center justify-between gap-4">
        <button
          data-testid="btn-prev"
          onClick={prev}
          disabled={current === 0}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted disabled:opacity-30 transition-all"
        >
          <i className="fa-solid fa-chevron-left text-xs" />
          Prev
        </button>

        {/* Dot indicators */}
        <div className="flex gap-1.5 overflow-x-auto max-w-xs">
          {cards.map((_, i) => (
            <button
              key={i}
              onClick={() => { setCurrent(i); setFlipped(false); }}
              className={`flex-shrink-0 w-2 h-2 rounded-full transition-all ${
                i === current
                  ? "bg-primary scale-125"
                  : statuses[i] === "known"
                  ? "bg-emerald-400"
                  : statuses[i] === "unknown"
                  ? "bg-red-400"
                  : "bg-border"
              }`}
            />
          ))}
        </div>

        <button
          data-testid="btn-next"
          onClick={next}
          disabled={current === cards.length - 1}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted disabled:opacity-30 transition-all"
        >
          Next
          <i className="fa-solid fa-chevron-right text-xs" />
        </button>
      </div>

      {/* End of deck */}
      {isEnd && (
        <div className="bg-card border border-border rounded-2xl p-6 text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto">
            <i className="fa-solid fa-flag-checkered text-primary text-lg" />
          </div>
          <div>
            <p className="font-bold text-foreground">Deck complete!</p>
            <p className="text-sm text-muted-foreground mt-1">
              <span className="text-emerald-400 font-semibold">{known}</span> known ·{" "}
              <span className="text-red-400 font-semibold">{unknown}</span> to review
            </p>
          </div>
          <button
            onClick={restart}
            className="flex items-center justify-center gap-2 mx-auto px-6 py-2.5 rounded-xl border border-border text-sm font-semibold text-muted-foreground hover:text-foreground hover:bg-muted transition-all"
          >
            <i className="fa-solid fa-rotate-left" />
            Restart Deck
          </button>
        </div>
      )}

      {/* All cards list */}
      <div className="bg-card border border-border rounded-2xl p-6">
        <h2 className="text-sm font-semibold text-foreground mb-4">All Cards ({cards.length})</h2>
        <div className="space-y-2 max-h-80 overflow-y-auto">
          {cards.map((card, i) => (
            <div
              key={i}
              data-testid={`flashcard-${i}`}
              onClick={() => { setCurrent(i); setFlipped(false); window.scrollTo({ top: 0, behavior: "smooth" }); }}
              className={`p-4 rounded-xl border cursor-pointer transition-all hover:shadow-sm ${
                i === current
                  ? "border-primary/40 bg-primary/5"
                  : statuses[i] === "known"
                  ? "border-emerald-400/25 bg-emerald-400/5"
                  : statuses[i] === "unknown"
                  ? "border-red-400/25 bg-red-400/5"
                  : "border-border hover:bg-muted/30"
              }`}
            >
              <div className="flex items-start gap-3">
                <div className={`w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 ${
                  statuses[i] === "known"   ? "bg-emerald-400/20" :
                  statuses[i] === "unknown" ? "bg-red-400/20" : "bg-muted"
                }`}>
                  <i className={`fa-solid text-[9px] ${
                    statuses[i] === "known"   ? "fa-check text-emerald-400" :
                    statuses[i] === "unknown" ? "fa-xmark text-red-400" : "fa-circle text-muted-foreground/40"
                  }`} />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-xs font-semibold text-primary mb-0.5">Q</p>
                  <p className="text-sm text-foreground leading-snug">{card.front}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
